### ISSUE TITLE
Sanitize storage keys

### ISSUE THREAD

**Issue by meranos** [SAP/InfraBox#391]
Currently some storage keys contain `//`. Due to a recent change minio (which is used for dev setup and validation) that service rejects objects with such an key. Aside of that those keys also cause issues when viewed in the gcs browser.

### To-Dos:
- [ ] fix cases where `//` keys are used
- [ ] Revert commit 7e12d3eb to go back to the latest minio version
- [ ] Allow transition period to new key style

**Comment by iberryful** [comment]
fixed
